name: Deploy Next.js to Cloudways

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Cloudways via SSH Password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e

            echo "Node Version:"
            node -v
            npm -v

            cd /home/bookwindow/htdocs/bookwindow.in

            echo "📥 Pulling latest code"
            git pull origin main

            echo "📦 Installing dependencies"
            npm install

            echo "🏗️ Building Next.js app"
            npm run build

            echo "♻️ Restarting PM2"
            pm2 restart all

            echo "✅ Deployment successful"
